### ISSUE TITLE
Create unit tests for add a new member and related code.

### ISSUE THREAD

**Issue by xSCIven** [RezziHD/Managing-Software-Projects-Repository#40]
- [x] #9

**Comment by xSCIven** [comment]
I am not sure if we should use a unit tester or playwright which does a complete end->end test. Creating unit tests for all code modules will be quite tedious. Playwright would be more efficient but it has a learning curve.

**Comment by henryennis** [comment]
Closed by #[32d574c](https://github.com/RezziHD/Managing-Software-Projects-Repository/commit/32d574c33fb1b43082aaf872cb23e32c7bd63610)
